# Generated by Django 4.2.1 on 2023-09-09 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('blog_content', models.TextField()),
                ('auther', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('blog_views', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=250, unique_for_date='time_stamp')),
                ('thumbnail', models.ImageField(default='', upload_to='blog')),
            ],
        ),
        migrations.CreateModel(
            name='Blogcomment',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
