# Generated by Django 4.2.1 on 2023-09-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(default='', max_length=100)),
                ('user_phone', models.CharField(default='', max_length=70)),
                ('message_content', models.TextField()),
                ('time_tamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
